# Generated by Django 4.2.1 on 2023-05-12 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+91xxxxxxxxxx'", regex='^\\+91(\\d{10})$')])),
                ('user_bio', models.TextField(blank=True, max_length=50)),
                ('instagram_link', models.URLField(blank=True, max_length=50)),
                ('facebook_link', models.URLField(blank=True, max_length=50)),
                ('profile_image', models.ImageField(upload_to='profile_pic/')),
            ],
        ),
    ]
