# Generated by Django 4.2.1 on 2023-05-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testmodel',
        ),
    ]
