# Generated by Django 4.2.1 on 2023-05-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_user_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(default='download.jpg', upload_to='thumbnailImages/'),
        ),
    ]
