# Generated by Django 4.2.1 on 2023-05-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogpost_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subblogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subBlogImages/'),
        ),
        migrations.AlterField(
            model_name='subblogpost',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subblogpost',
            name='subheading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subblogpost',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
