# Generated by Django 4.2.1 on 2023-05-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_subblogpost_image_alter_subblogpost_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comment', to='blog.comment'),
        ),
    ]
