# Generated by Django 4.2.1 on 2023-05-31 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_admincomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admincomment',
            old_name='commment',
            new_name='comment',
        ),
    ]
