# Generated by Django 4.2.1 on 2023-06-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='resolved_status',
            field=models.BooleanField(default=False),
        ),
    ]
